# Generated by Django 5.0.12 on 2025-03-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("HR", "HR"),
                    ("Manager", "Manager"),
                    ("Employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
