# Generated by Django 5.0.12 on 2025-03-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
