# Generated by Django 5.0.12 on 2025-03-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_force_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='force_password_change',
        ),
    ]
