# Generated by Django 5.0.12 on 2025-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HOD', 'HOD'), ('HR Manager', 'HR Manager'), ('Employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
