# Generated by Django 5.0.12 on 2025-03-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("HOD", "HOD"),
                    ("HR Manager", "HR Manager"),
                    ("Employee", "Employee"),
                ],
                default="Employee",
                max_length=20,
            ),
        ),
    ]
