# Generated by Django 5.0.12 on 2025-03-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
