# Generated by Django 5.0.12 on 2025-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_hire",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_position",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
