# Generated by Django 5.0.12 on 2025-03-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="other_names",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
