# Generated by Django 5.0.12 on 2025-03-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_employee_other_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="salary",
        ),
    ]
