# Generated by Django 5.0.12 on 2025-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=10)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('record_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'audit_log_154',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuditUserLogin',
        ),
    ]
