# Generated by Django 5.0.12 on 2025-03-04 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0004_remove_employee_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_154",
                "managed": True,
            },
        ),
    ]
