# Generated by Django 5.0.12 on 2025-03-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True),
        ),
    ]
