# Generated by Django 5.0.12 on 2025-03-11 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_salary'),
        ('information', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
            preserve_default=False,
        ),
    ]
