# Generated by Django 5.0.12 on 2025-03-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="attendance",
            table="attendance_154",
        ),
    ]
