# Generated by Django 5.0.12 on 2025-03-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_options_alter_attendance_table"),
        ("employee", "0004_remove_employee_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick", "Sick Leave"),
                            ("Vacation", "Vacation"),
                            ("Unpaid", "Unpaid Leave"),
                            ("Maternity", "Maternity Leave"),
                            ("Paternity", "Paternity Leave"),
                            ("Bereavement", "Bereavement Leave"),
                            ("Study", "Study Leave"),
                            ("Compassionate", "Compassionate Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "db_table": "leave_154",
                "managed": True,
            },
        ),
    ]
